version = "1.0.1"
# Requires a version of numpy with a `py.typed` file
requires = ["numpy>=1.20", "pandas-stubs", "types-shapely", "pyproj"]
requires_python = ">=3.9"
upstream_repository = "https://github.com/geopandas/geopandas"
